config/routes.rb
Rails.application.routes.draw do
  # Home
  get '/' => 'sessions#new'
  
  # Search
  get '/students/search' => 'students#search'
  
  # Login/Logout/Signup
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users, only: [:new, :create]

  # Classrooms
  resources :classrooms
  resources :classrooms, only: [:show] do
    resources :students, only: [:index, :new]
    get '/add_students' => 'classrooms#students_to_associate'
    post '/add_students' => 'classrooms#associate_students'
    get '/students/with_allergy' => 'students#with_allergy'
    post '/remove_student' => 'classrooms#remove_association'
  end
  
  # Students
  post '/students/batch' => 'students#batch_create'  
  get '/students/with_allergy' => 'students#with_allergy'
  resources :students
  resources :students, only: [:show] do
    resources :allergies, only: [:new]
  end
  
  # Allergies
  resources :allergies, only: [:new, :destroy]
  post '/allergies' => 'allergies#create'
  
  # Severities
  resources :severities, only: [:destroy]


  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :user
  has_many :enrollments
  has_many :students, through: :enrollments
  validates :period, numericality: { only_integer: true, greater_than: 0 }
  validates :subject, presence: true
  validates :teacher, presence: true

  def allergy_count
    count = 0
    self.students.each{|s| count += s.allergies.count}
    count
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :verify_logged_in

  def index
    @classrooms = current_user.classrooms
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to classroom_add_students_path(@classroom)
    else
      render :new
    end
  end

  def students_to_associate
    @classroom = Classroom.find_by(id: params[:classroom_id])
    @students = Student.all
    render :associate_students
  end

  def associate_students
    student_ids = params[:student].keys.map{|k| k.to_i}
    student_ids.each do |s_id|
      Enrollment.create(student_id: s_id, classroom_id: params[:classroom_id])
    end
    redirect_to classroom_students_path(params[:classroom_id])
  end

  def remove_association
    enrollment = Enrollment.find_by(student: params[:student_id], classroom: params[:classroom_id])
    enrollment.destroy
    flash[:alert] = "Student removed from class"
    redirect_back fallback_location: classroom_students_path(params[:classroom_id]) 
  end

  def edit
    @classroom = Classroom.find(params[:id])
    verify_user
  end

  def update
    @classroom = Classroom.find(params[:id])
    verify_user
    @classroom.update(classroom_params)

    if @classroom.save
      redirect_to @classroom
    else
      render :edit
    end
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    verify_user
    @classroom.enrollments.destroy_all
    @classroom.destroy
    flash[:alert] = "Class deleted"
    redirect_to classrooms_path
  end

  private

  def classroom_params
    params.require(:classroom).permit(:period, :subject, :teacher, :user_id)
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %><br>
  <%= f.label :period %>
  <%= f.number_field :period, min: 1, step: 1 %><br>
  <%= f.label :teacher %>
  <%= f.text_field :teacher %><br>

  <%= f.hidden_field :user_id, value: current_user.id %><br>
  <%= f.submit %><br>
<% end %>

app/views/classrooms/associate_students.html.erb
<h3><%= "Period #{@classroom.period} #{@classroom.subject} with #{@classroom.teacher}" %></h4>

<%= link_to "Skip For Now", classrooms_path %><br><br>

<b style="padding-left: 100px;">Select Students To Add</b><br><br>


<%= form_tag "/classrooms/#{@classroom.id}/add_students", method: "post" do %>
  <table>
    <tr>
      <th style="padding-left: 15px;">Add? </th>
      <th style="padding-left: 15px;">Last Name </th>
      <th style="padding-left: 15px;">First Name </th> 
      <th style="padding-left: 15px;">Grade </th>
      <th style="padding-left: 15px;">Lunch </th>
    </tr>
    <% @students.sort_by{ |s| s.last_name}.each do |s| %>
      <tr>
        <td style="padding-left: 20px;"><%= check_box_tag "student[#{s.id}]" %></td>
        <td style="padding-left: 15px;"><%= s.last_name %></td> 
        <td style="padding-left: 15px;"><%= s.first_name %></td>
        <td style="padding-left: 15px;"><%= s.grade %></td> 
        <td style="padding-left: 15px;"><%= s.lunch_period %></td>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Add Students To Class" %><br><br>
<% end %>

app/views/classrooms/edit.html.erb
<h2>Edit Class</h2>
<%= render partial: "layouts/errors", locals: {obj: @classroom} %>
<%= render "form" %>

<br><br><br><%= button_to "Delete Class", classroom_path(@classroom), method: :delete %>

app/views/classrooms/index.html.erb
<h2>My Classes</h2>

<%= button_to "Add Class", new_classroom_path, method: :get %>

<ul>
  <% @classrooms.sort_by{ |c| c.period}.each do |c| %>
    <li>
      <%= c.subject %> - Period <%= c.period %><br>
      Teacher: <%= c.teacher %><br>
      <%= link_to "Student Roster", classroom_students_path(c)%>: <%= pluralize(c.students.count, "student") %> <br>
      Allergies or special considerations: <%= c.allergy_count %><br><br>
      <%= link_to "Edit Class Info", edit_classroom_path(c) %> || 
      <%= link_to "Add Students To Class", classroom_add_students_path(c) %> ||
      <%= link_to "Create New Student", new_classroom_student_path(c) %> <br><br><br>
    </li>
  <% end %>
</ul>

app/views/classrooms/new.html.erb
<h2>New Classroom</h2>
<%= render partial: "layouts/errors", locals: {obj: @classroom} %>
<%= render "form" %>