config/routes.rb
Rails.application.routes.draw do
  # Home
  get '/' => 'sessions#new'
  
  # Search
  get '/students/search' => 'students#search'
  
  # Login/Logout/Signup
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users, only: [:new, :create]

  # Classrooms
  resources :classrooms
  resources :classrooms, only: [:show] do
    resources :students, only: [:index, :new]
    get '/add_students' => 'classrooms#students_to_associate'
    post '/add_students' => 'classrooms#associate_students'
    get '/students/with_allergy' => 'students#with_allergy'
    post '/remove_student' => 'classrooms#remove_association'
  end
  
  # Students
  post '/students/batch' => 'students#batch_create'  
  get '/students/with_allergy' => 'students#with_allergy'
  resources :students
  resources :students, only: [:show] do
    resources :allergies, only: [:new]
  end
  
  # Allergies
  resources :allergies, only: [:new, :destroy]
  post '/allergies' => 'allergies#create'
  
  # Severities
  resources :severities, only: [:destroy]


  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :enrollments
  has_many :classrooms, through: :enrollments
  has_many :severities
  has_many :allergies, through: :severities
  
  validates :first_name, :last_name, :lunch_period, presence: true
  validates :grade, numericality: { only_integer: true, greater_than: 0 }
  
  scope :has_allergy, -> { joins(:allergies).uniq }

  def display_allergies
    self.severities.map{|s| "#{s.allergy.category}: #{s.allergy.name} - Requires #{s.level}"}
  end

  def self.last_name_search(query)
    Student.where("last_name LIKE ?", "%#{query}%")
  end 

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :verify_logged_in
  PERMITTED_PARAMS = [:first_name, :last_name, :grade, :lunch_period]

  def search
    @students = Student.last_name_search(params[:search])
    render :index
  end 

  def index
    if params[:classroom_id]
      @classroom = Classroom.find(params[:classroom_id])
      verify_user
      @students = @classroom.students
    else
      @students = Student.all.sort_by{ |s| s.last_name}
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def with_allergy
    if params[:classroom_id]
      @classroom = Classroom.find(params[:classroom_id])
      verify_user
      @students = @classroom.students.has_allergy.sort_by{ |s| s.last_name}
    else
      @students = Student.has_allergy.sort_by{ |s| s.last_name}
    end
  end

  def new
    if params[:classroom_id]
      @classroom = Classroom.find(params[:classroom_id])
      verify_user
      @student = Student.new
    elsif params[:student_count]
      @student_count = params[:student_count].to_i
    else
      @student = Student.new
    end
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      if params[:student][:classrooms]
        Enrollment.create(student_id: @student.id, classroom_id: params[:student][:classrooms])
      end
      if params[:student][:allergy_count] == "0"
        redirect_to @student
      else 
        @allergy_count = params[:student][:allergy_count].to_i
        @allergy = Allergy.new
        @allergies = Allergy.all.sort_by{|a| a.name}
        render '/allergies/new'
      end
    else
      render :new
    end
  end

  def batch_create
    params[:student].keys.each do |key|
      args = params[:student][key] 
      if args.keys.map{|k| k.to_sym} == PERMITTED_PARAMS
        args.permit!
        student = Student.new(args)
        if student.save
          next
        else
          flash[:alert] = "Could not create student batch. Please fill in all fields before submitting"
          redirect_to(students_path) and return
        end
      end
    end   
    redirect_to students_path 
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    @student.update(student_params)

    if @student.save
      redirect_to @student
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.severities.destroy_all
    @student.destroy
    flash[:alert] = "Student deleted"
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(*PERMITTED_PARAMS)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= f.label :first_name %>
<%= f.text_field :first_name %><br>
<%= f.label :last_name %>
<%= f.text_field :last_name %><br>
<%= f.label :grade %>
<%= f.number_field :grade %><br>
<%= f.label :lunch_period %>
<%= f.text_field :lunch_period %><br><br>

app/views/students/edit.html.erb
<h2>Edit Student</h2>
<%= render partial: "layouts/errors", locals: {obj: @student} %>
<%= form_for @student do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit %>
<% end %>

<br><br>To add an allergy instead click <%= link_to "here", new_student_allergy_path(@student) %>

app/views/students/index.html.erb
<% if @classroom %>
  <h2>Student Roster</h2>
  <h4><%= "Period #{@classroom.period} #{@classroom.subject} with #{@classroom.teacher}" %></h4>
  <%= link_to "See Only Students With Allergies", classroom_students_with_allergy_path(@classroom) %><br><br>
<% else %>
  <h2>All Students</h2>
  <%= link_to "See Only Students With Allergies", students_with_allergy_path %><br><br>
<% end %>
<b> * indicates student with allergy</b><br><br>

<%= form_tag '/students/search', method: 'get' do %>
  <%= label_tag "Search by Last Name" %>
  <%= text_field_tag "search" %>
  <%= submit_tag "Search" %>
<% end %>





<table>
  <tr>
    <th>Last Name </th>
    <th>First Name </th> 
    <th>Grade </th>
    <th>Lunch </th>
    <th>Detail </th>
    <th>Edit </th>
    <th>Remove </th>
  </tr>
  <% @students.each do |s| %>
    <tr>
      <td><%= "* " if s.allergies.count > 0 %><%= s.last_name %></td> 
      <td><%= s.first_name %></td>
      <td><%= s.grade %></td> 
      <td><%= s.lunch_period %></td>
      <td><%= link_to "Detail", student_path(s) %></td>
      <td><%= link_to "Edit", edit_student_path(s) %></td>
      <% if @classroom %>
        <td>
          <%= form_tag classroom_remove_student_path(@classroom), method: "post" do %>
            <%= hidden_field_tag "student_id", s.id %>
            <%= submit_tag "Remove" %>
          <% end %>
        </td>
      <% else %>
        <td><%= button_to "Delete", student_path(s), method: :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<% if @classroom && @students.empty? %>
  <br><b style="color:red; padding-left: 50px;">This class doesn't have any students yet!</b><br><br><br>
<% end %>

<% if !@classroom %>
  <br><br><b>Add Multiple Students At Once?</b>
  <%= form_tag '/students/new', method: 'get' do %>
    <%= label_tag "How many Students?" %>
    <%= number_field_tag 'student_count', 2 , min: 2, max: 20, step: 1 %><br>
    <%= submit_tag "Create New Batch" %><br><br>
  <% end %>
<% else %>
  <br><%= link_to "Add students to this class", classroom_add_students_path(@classroom) %>
  <br><br><%= button_to "Delete This Class", classroom_path(@classroom), method: :delete %>
<% end %>

app/views/students/new.html.erb
<% if @classroom %>
  <%= render partial: "layouts/errors", locals: {obj: @student} %>
  <h2>New Student For:</h2>
  <h4><%= "Period #{@classroom.period} #{@classroom.subject} with #{@classroom.teacher}" %></h4>
  <%= form_for @student do |f| %>
    <%= render partial: "form", locals: {f: f} %>
    <%= f.label "Number of allergies" %>
    <%= f.number_field :allergy_count, in: 0..5, value: 0 %><br>

    <%= f.hidden_field :classrooms, value: @classroom.id %><br>
    <%= f.submit %>
  <% end %>

<% elsif @student_count %>
  <h2>New Batch of Students</h2>
  ** Make sure to fill in all boxes or your request will not be accepted **<br><br> 

  <%= form_tag "/students/batch", method: "post" do %>
    <% @student_count.times do |count| %>
      <% count += 1 %>
      <b>Student <%= count %>: </b><br>
      <%= label_tag "First Name" %>
      <%= text_field_tag "student[#{count}][first_name]" %><br>
      <%= label_tag "Last Name" %>
      <%= text_field_tag "student[#{count}][last_name]" %><br>
      <%= label_tag "Grade" %>
      <%= number_field_tag "student[#{count}][grade]", nil , min: 0, max: 12, step: 1 %><br>
      <%= label_tag "Lunch Period" %>
      <%= text_field_tag "student[#{count}][lunch_period]" %><br><br>
    <% end %>
  <%= submit_tag "Create All" %>
  <% end %>

<% else %>
  <%= render partial: "layouts/errors", locals: {obj: @student} %>
  <h2>New Student</h2>
  <%= form_for @student do |f| %>
    <%= render partial: "form", locals: {f: f} %>
    <%= f.label "Number of allergies" %>
    <%= f.number_field :allergy_count, in: 0..5, value: 0 %><br>
    <br>
    <%= f.submit %>
  <% end %>
<% end %>
  

app/views/students/show.html.erb
<h2><%= @student.first_name + " " + @student.last_name %></h2> 
Grade: <%= @student.grade %><br>
Lunch Period: <%= @student.lunch_period %><br>

<% if !@student.display_allergies.empty? %>
  <% @student.display_allergies.each.with_index do |a, index| %>
    <b style="color:red;"><%= a %></b> <%= button_to "Remove Allergy #{index + 1}", severity_path(@student.severities[index]), method: :delete %>
  <% end %>
  <br><br>
<% else %>
    No allergies<br><br>
<% end %>
<%= button_to "Add Allergy", new_student_allergy_path(@student), method: :get %><br><br>

<%= button_to "Edit Student Info", edit_student_path(@student) %>
<%= button_to "Delete Student", student_path(@student), method: :delete %><br>


<h3>Class Schedule:</h3>
<ul>
  <% @student.classrooms.sort_by{ |c| c.period }.each do |c| %>
    <li>
      <b>Period <%= c.period %></b><br>
      Subject: <%= c.subject %><br>
      Teacher: <%= c.teacher %><br><br>
    </li>
  <% end %>
</ul>

app/views/students/with_allergy.html.erb
<% if @classroom %>
  <h2>Students With Allergies</h2>
  <h4><%= "Period #{@classroom.period} #{@classroom.subject} with #{@classroom.teacher}" %></h4>
<% else %>
  <h2>All Students With Allergies</h2>
<% end %>

<% if @students.empty? %>
  <br><b style="color:red; padding-left: 50px;">No Students in this class have allergies!</b>
<% else %>
  <ul>
    <% @students.each do |s| %>
      <li>
        <b><%= "#{s.last_name}, #{s.first_name}" %></b><br><br> 
        <%= "Grade: #{s.grade} - Lunch Period: #{s.lunch_period}" %><br>
        <% s.display_allergies.each.with_index do |a, index| %>
          <b style="color:red;"><%= a %></b> <%= button_to "Remove Allergy #{index + 1}", severity_path(s.severities[index]), method: :delete %>
        <% end %>
        <br>
      </li>
    <% end %>
  </ul>
<% end %>