config/routes.rb
Rails.application.routes.draw do
  # Home
  get '/' => 'sessions#new'
  
  # Search
  get '/students/search' => 'students#search'
  
  # Login/Logout/Signup
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users, only: [:new, :create]

  # Classrooms
  resources :classrooms
  resources :classrooms, only: [:show] do
    resources :students, only: [:index, :new]
    get '/add_students' => 'classrooms#students_to_associate'
    post '/add_students' => 'classrooms#associate_students'
    get '/students/with_allergy' => 'students#with_allergy'
    post '/remove_student' => 'classrooms#remove_association'
  end
  
  # Students
  post '/students/batch' => 'students#batch_create'  
  get '/students/with_allergy' => 'students#with_allergy'
  resources :students
  resources :students, only: [:show] do
    resources :allergies, only: [:new]
  end
  
  # Allergies
  resources :allergies, only: [:new, :destroy]
  post '/allergies' => 'allergies#create'
  
  # Severities
  resources :severities, only: [:destroy]


  

  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" style="color:red;">
    <b><%= pluralize(obj.errors.count, "error") %> occurred: </b>

    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentAllergies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  <% unless !logged_in? %>
    <br>
    <a style="padding-left: 80px;"><%= link_to "My Classes", classrooms_path %></a>
    <a style="padding-left: 80px;"><%= link_to "New Class", new_classroom_path %></a> 
    <a style="padding-left: 80px;"><%= link_to "All Students", students_path %></a>
    <a style="padding-left: 80px;"><%= link_to "Log Out", logout_path %></a>
  <% end %>
  <br><br><b style="color:red;"><%= flash[:alert] %></b>

    <%= yield %>

  </body>
</html>